server:
  port: 50101 #${PORT:50101}                     # 服务端口
spring:
  application:
    name: yo-govern-center
eureka:
  client:
    register-with-eureka: true            # 服务注册，是否将自己注册到Eureka服务中
    fetch-registry: true                  # 服务发现，是否从Eureka中获取注册信息
    service-url:                          # Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://localhost:50101/eureka/ #${EUREKA_SERVER:http://eureka02:50102/eureka/}
  server:
    enable-self-preservation: false       # 是否开启自我保护模式 开发阶段关闭
    eviction-interval-timer-in-ms: 60000  # 服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: eureka01 #${EUREKA_DOMAIN:eureka01}