server:
  port: 31450
spring:
  application:
    name: yo-service-media-processor
  data:
    mongodb:
      uri: mongodb://192.168.204.130:27017
      database: yo_media
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.130:3306/yoyo?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Liu.2020
    hikari:
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 15           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 30000             # 最大空闲时长
      pool-name: DatebookHikariCP     # 连接池名
      max-lifetime: 900000            # 最大生命周期
      connection-timeout: 30000       # 连接超时时间
      connection-test-query: SELECT 1 # 心跳检测
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #rabbitmq配置
  rabbitmq:
    host: 192.168.204.130
    port: 5672
    username: lhy
    password: yhl
    virtual-host: /
    publisher-returns: true # 开启returnedMessage回调 Exchange -> Queue
    publisher-confirms: true # 开启confirms回调 P -> Exchange
    listener:
      simple:
        acknowledge-mode: manual # 手动返回ACK
        prefetch: 100
        # 指示容器是否随着ApplicationContext的启动而启动。
        # 设置这个值为false，如果在你启动的时候消息代理还没有启动，当消息代理准备好的时候调用start()方法手动启动。
        auto-startup: true
        default-requeue-rejected: false # 不重回队列
    template:
      mandatory: true

yo-service-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: D:/Project/yoyo_video/
  ffmpeg-path: D:/ffmpeg/ffmpeg/bin/ffmpeg.exe