server:
  port: 31200
spring:
  application:
    name: yo-service-video-manage
  data:
    mongodb:
      uri:  mongodb://192.168.204.130:27017
      database: yo_media
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.130:3306/yoyo?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Liu.2020
    hikari:
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 15           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 30000             # 最大空闲时长
      pool-name: DatebookHikariCP     # 连接池名
      max-lifetime: 900000            # 最大生命周期
      connection-timeout: 30000       # 连接超时时间
      connection-test-query: SELECT 1 # 心跳检测
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#Mybatis
mybatis:
  mapper-locations: com.you.xml.*.xml         #xml文件
  #type-aliases-package: com.you.domain.course #model路径
#Eureka
eureka:
  client:
    registerWithEureka: true                # 服务注册开关
    fetchRegistry: true                     # 服务发现开关
    serviceUrl:                             # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true                # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id
ribbon:
  MaxAutoRetries: 2                         # 最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3               # 切换实例的重试次数
  OkToRetryOnAllOperations: false           # 对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000                      # 请求连接的超时时间
  ReadTimeout: 6000                         # 请求处理的超时时间

yo-service-video-manage:
  upload-location: D:/Project/yoyo_video/
  video-site-id: 5e7d81f14bb8f147dca0a597
  video-template-id: 5e85944e4bb8f174542b8511
  video-pageWebPath: /play
  video-pagePhysicalPath: /play
  video-dataModel-url: http://localhost:31200/video/findVideoModelById/
  video-preViewUrl: http://192.168.204.130:88/cms/view/